### ISSUE TITLE
Install shown error

### ISSUE THREAD

**Issue by newbie2005** [DevinY/dlaravel#6]
$ ./create demo
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 41, in project_from_options
  File "compose\cli\command.py", line 109, in get_project
  File "compose\config\config.py", line 283, in find
  File "compose\config\config.py", line 283, in <listcomp>
  File "compose\config\config.py", line 183, in from_filename
  File "compose\config\config.py", line 1434, in load_yaml
  File "site-packages\yaml\__init__.py", line 94, in safe_load
  File "site-packages\yaml\__init__.py", line 70, in load
  File "site-packages\yaml\loader.py", line 24, in __init__
  File "site-packages\yaml\reader.py", line 85, in __init__
  File "site-packages\yaml\reader.py", line 124, in determine_encoding
  File "site-packages\yaml\reader.py", line 178, in update_raw
UnicodeDecodeError: 'cp950' codec can't decode byte 0xa0 in position 33: illegal multibyte sequence
[8472] Failed to execute script docker-compose
dlaravel_php_1 is not running.

**Comment by DevinY** [comment]
我可以知道您使用的docker-compose版本嗎?
docker-compose version

是否可嚐試更新您的docker-compose看看?
https://docs.docker.com/compose/install/
